# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'debugproject' do
  pod 'AppCenter/Crashes', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for debugproject

  

  platform :ios, '9.0'
  target 'debugprojectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'debugproject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for debugproject-tvOS

  target 'debugproject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
